# Generated by Django 2.2.4 on 2019-09-04 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('fileitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.FileItem')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document',
            },
            bases=('klazor.fileitem',),
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'narrator',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libr.Document')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('lang_alpha2', models.CharField(blank=True, max_length=2, null=True)),
                ('author_set', models.ManyToManyField(to='libr.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.Publisher')),
            ],
            options={
                'db_table': 'book',
            },
            bases=('libr.document',),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libr.Document')),
                ('nb_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_file',
            },
            bases=('libr.document',),
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libr.Book')),
                ('nb_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper_book',
            },
            bases=('libr.book',),
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libr.Book')),
                ('narrator_set', models.ManyToManyField(blank=True, to='libr.Author')),
            ],
            options={
                'db_table': 'audio_book',
            },
            bases=('libr.book',),
        ),
    ]
