from django.contrib import admin
from klazor.models import *

admin.site.register(Course)
admin.site.register(Topic)
admin.site.register(FileItem)
admin.site.register(CourseElement)
admin.site.register(CoursePart)
admin.site.register(Instructor)
admin.site.register(School)
admin.site.register(VideoCell)
admin.site.register(AudioCell)
admin.site.register(FileCell)
admin.site.register(MarkdownCell)
admin.site.register(NumericalQuestionCell)
admin.site.register(OpenEndedQuestionCell)
admin.site.register(MultipleChoiceQuestionCell)
admin.site.register(Proposition)
admin.site.register(ImageCell)
admin.site.register(Sheet)
admin.site.register(Folder)
