# Generated by Django 2.2.3 on 2019-07-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
    ]
