# Generated by Django 2.2.1 on 2019-06-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
