# Generated by Django 2.2.4 on 2019-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubecell',
            old_name='youtube',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='audiocell',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='imagecell',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videocell',
            name='video',
        ),
        migrations.AddField(
            model_name='audiocell',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecell',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocell',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
