# Generated by Django 2.2.4 on 2019-08-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_auto_20190812_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiocell',
            old_name='url',
            new_name='audio_url',
        ),
        migrations.RenameField(
            model_name='filecell',
            old_name='url',
            new_name='file_url',
        ),
        migrations.RenameField(
            model_name='imagecell',
            old_name='url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='videocell',
            old_name='url',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='youtubecell',
            old_name='url',
            new_name='youtube_url',
        ),
    ]
