# Generated by Django 2.2.1 on 2019-06-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0002_auto_20190606_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klazor.Folder'),
        ),
    ]
