# Generated by Django 2.2.1 on 2019-06-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0003_auto_20190606_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Item')),
                ('fil', models.FileField(upload_to='files')),
            ],
            options={
                'db_table': 'file',
            },
            bases=('klazor.item',),
        ),
    ]
