# Generated by Django 2.2.4 on 2019-08-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0003_auto_20190812_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiocell',
            old_name='audio_url',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='filecell',
            old_name='file_url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imagecell',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='videocell',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='youtubecell',
            old_name='youtube_url',
            new_name='youtube',
        ),
    ]
