# Generated by Django 2.2.2 on 2019-07-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0003_auto_20190705_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klazor.Course'),
        ),
    ]
