# Generated by Django 2.2.1 on 2019-06-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0004_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileItem',
        ),
        migrations.RenameField(
            model_name='fileitem',
            old_name='fil',
            new_name='file',
        ),
    ]
