# Generated by Django 2.2.2 on 2019-07-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0005_auto_20190705_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseelement',
            name='completed',
        ),
    ]
