# Generated by Django 2.2.2 on 2019-07-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0006_remove_courseelement_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepart',
            old_name='type',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admissions_link',
        ),
        migrations.RemoveField(
            model_name='school',
            name='programs_link',
        ),
    ]
