# Generated by Django 2.2.1 on 2019-06-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0006_auto_20190606_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
