# Generated by Django 2.2.2 on 2019-07-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('klazor', '0008_auto_20190706_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_klazor.instructor_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='school',
            name='colloquial_name',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
