# Generated by Django 2.2.2 on 2019-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0009_auto_20190706_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
