# Generated by Django 2.2.3 on 2019-07-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klazor', '0013_auto_20190707_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeCell',
            fields=[
                ('cell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='klazor.Cell')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('scale', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'youtube_cell',
            },
            bases=('klazor.cell',),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
